from . import account_move
from . import event_registration
from . import iz_subscription_benefit
from . import iz_subscription_plan
from . import product_template
from . import res_partner
from . import sale_order
from . import sale_order_line
from . import sale_subscription
from . import sale_subscription_close_reason
from . import sale_subscription_line
from . import sale_subscription_stage
from . import sale_subscription_tag
from . import sale_subscription_template
