# Copyright 2023 Domatix - Carlos Martínez
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
{
    "name": "Iron Zone - Suscripciones",
    "summary": "Gestiona suscripciones, productos recurrentes y facturacion periodica.",
    "version": "18.0.1.0.0",
    "development_status": "Beta",
    "category": "Subscription Management",
    "website": "https://github.com/OCA/contract",
    "license": "AGPL-3",
    "author": "Domatix, Onestein, Odoo Community Association (OCA)",
    "depends": [
        "sale_management",
        "account",
        "event",
        "website",
        "portal",
        "website_event_sale",
    ],
    "data": [
        "views/product_template_views.xml",
        "views/account_move_views.xml",
        "views/sale_subscription_views.xml",
        "views/iz_subscription_plan_views.xml",
        "views/sale_subscription_stage_views.xml",
        "views/sale_subscription_tag_views.xml",
        "views/sale_subscription_template_views.xml",
        "views/sale_order_views.xml",
        "views/res_partner_views.xml",
        "views/event_registration_views.xml",
        "views/website_event_subscription_views.xml",
        "data/ir_cron.xml",
        "data/sale_subscription_data.xml",
        "wizard/close_subscription_wizard.xml",
        "views/portal_subscription_views.xml",
        "security/ir.model.access.csv",
    ],
    "installable": True,
    "application": True,
}
